import {
  Atom,
  BookOpen,
  Brain,
  Briefcase,
  Clapperboard,
  Code2,
  Cog,
  Landmark,
  Palette,
  PiggyBank,
  Scale,
  Sigma,
  Stethoscope,
  Theater,
  type LucideIcon,
} from "lucide-react";

export const FIELD_ICON: Record<string, LucideIcon> = {
  cs: Code2,
  engineering: Cog,
  math: Sigma,
  science: Atom,
  medicine: Stethoscope,
  business: Briefcase,
  economics: PiggyBank,
  law: Scale,
  social: Brain,
  humanities: BookOpen,
  design: Palette,
  architecture: Landmark,
  arts: Theater,
  media: Clapperboard,
};
