-- =====================================================================
-- UniRoute — reference data: 15 real universities + 16 real scholarships
--
-- ДЕМОНСТРАЦИОННЫЕ ДАННЫЕ. Университеты, стипендии, ссылки и фото —
-- реальные, но цифры (стоимость, проходные баллы, доля поступивших,
-- дедлайны) — ориентировочные значения на цикл поступления 2026/27.
-- Перед подачей всегда сверяйтесь с официальным сайтом (website_url).
--
-- Фото: Wikimedia Commons, лицензии указаны в image_credit.
-- Рейтинг: QS World University Rankings (ориентировочно).
-- =====================================================================

insert into public.universities (
  slug, name, name_ru, country, country_code, city,
  qs_rank, acceptance_rate, tuition_usd_per_year, living_cost_usd_per_year,
  min_gpa_4, avg_gpa_4, min_ielts, min_toefl, sat_required, sat_recommended,
  entrance_exams, requires_foundation, foundation_note,
  instruction_languages, fields, programs,
  scholarship_level, scholarship_note, application_deadlines, intake,
  description, highlights,
  image_url, image_credit, image_source_url,
  website_url, admissions_url, data_source, is_demo, data_updated_at
) values
(
  'mit', 'Massachusetts Institute of Technology', 'Массачусетский технологический институт',
  'США', 'US', 'Кембридж',
  1, 4.5, 64000, 22000,
  3.90, 3.97, 7.0, 100, true, 1540,
  '{SAT}', false, null,
  '{English}', '{cs,engineering,science,math,economics,business}',
  '{"Computer Science","Electrical Engineering","Mathematics","Physics","Economics","Mechanical Engineering"}',
  'full', 'Need-blind приём для всех, включая иностранцев: MIT покрывает 100% подтверждённой финансовой потребности семьи.',
  '[{"label":"Early Action","month":11,"day":1},{"label":"Regular Action","month":1,"day":5}]', 'Сентябрь',
  'Лучший технический вуз мира по QS. Сильнейшие программы в инженерии, CS и точных науках, культура «mens et manus» — учиться, делая.',
  '{"№1 в мире по QS","Полная финансовая помощь по потребности","UROP — исследования с первого курса"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/Great_dome_of_MIT%2C_Feb_2021_%282%29_%28cropped%29.jpg/1280px-Great_dome_of_MIT%2C_Feb_2021_%282%29_%28cropped%29.jpg',
  'Peacearth · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Great_dome_of_MIT,_Feb_2021_(2)_(cropped).jpg',
  'https://www.mit.edu', 'https://mitadmissions.org/apply/',
  'mitadmissions.org, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'asu', 'Arizona State University', 'Университет штата Аризона',
  'США', 'US', 'Темпе',
  200, 90.0, 36000, 16000,
  3.00, 3.50, 6.0, 61, false, null,
  '{}', false, null,
  '{English}', '{engineering,business,cs,design,arts,science,media}',
  '{"Software Engineering","Business Administration","Sustainability","Graphic Design","Journalism","Aerospace Engineering"}',
  'partial', 'New American University International Scholarship — автоматическое рассмотрение при подаче, частичное покрытие обучения.',
  '[{"label":"Рекомендуемый срок (осень)","month":5,"day":1}]', 'Август',
  'Крупнейший и один из самых инновационных университетов США с гибкими требованиями и огромным выбором программ.',
  '{"Высокий шанс поступления","SAT не требуется","№1 по инновациям в США (US News)"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/2021_Arizona_State_University%2C_Tempe_Campus%2C_Old_Main.jpg/1280px-2021_Arizona_State_University%2C_Tempe_Campus%2C_Old_Main.jpg',
  'Beyond My Ken · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:2021_Arizona_State_University,_Tempe_Campus,_Old_Main.jpg',
  'https://www.asu.edu', 'https://admission.asu.edu/apply/international',
  'admission.asu.edu, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'toronto', 'University of Toronto', 'Университет Торонто',
  'Канада', 'CA', 'Торонто',
  29, 43.0, 47000, 15000,
  3.50, 3.80, 6.5, 100, false, 1400,
  '{}', false, null,
  '{English}', '{cs,engineering,science,business,economics,medicine,humanities,social}',
  '{"Computer Science","Engineering Science","Life Sciences","Rotman Commerce","Economics","Psychology"}',
  'limited', 'Lester B. Pearson — полная стипендия, но очень высокий конкурс (≈37 наград в год). Нужна номинация школы.',
  '[{"label":"Номинация на Pearson","month":11,"day":7},{"label":"Основной дедлайн","month":1,"day":15}]', 'Сентябрь',
  'Ведущий университет Канады: сильная наука, программа co-op и возможность остаться работать после выпуска (PGWP).',
  '{"Топ-30 мира","Разрешение на работу после выпуска до 3 лет","Стипендия Lester B. Pearson"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Toronto_University_College_1.jpg/1280px-Toronto_University_College_1.jpg',
  'GoginkLobabi · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Toronto_University_College_1.jpg',
  'https://www.utoronto.ca', 'https://future.utoronto.ca/applying',
  'future.utoronto.ca, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'ucl', 'University College London', 'Университетский колледж Лондона',
  'Великобритания', 'GB', 'Лондон',
  9, 30.0, 45000, 22000,
  3.60, 3.85, 7.0, 100, false, null,
  '{"A-levels / IB / Foundation"}', true,
  'Аттестата 11 классов недостаточно: нужен IB, A-levels, Foundation-год (например, UCL UPC) или первый курс вуза.',
  '{English}', '{medicine,architecture,cs,economics,law,humanities,science,engineering,social}',
  '{"Economics","Computer Science","Architecture (Bartlett)","Law","Medicine","Psychology"}',
  'limited', 'UCL Global Undergraduate Scholarship — для студентов из семей с низким доходом, мест немного.',
  '[{"label":"Медицина (UCAS)","month":10,"day":15},{"label":"UCAS — основной дедлайн","month":1,"day":14}]', 'Сентябрь',
  'Один из самых престижных вузов Европы в центре Лондона. Сильнейшие программы в экономике, архитектуре и медицине.',
  '{"Топ-10 мира","Центр Лондона","Бакалавриат за 3 года"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/UCL_Portico_Building.jpg/1280px-UCL_Portico_Building.jpg',
  'LordHarris · CC BY-SA 3.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:UCL_Portico_Building.jpg',
  'https://www.ucl.ac.uk', 'https://www.ucl.ac.uk/prospective-students/undergraduate',
  'ucl.ac.uk, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'manchester', 'The University of Manchester', 'Манчестерский университет',
  'Великобритания', 'GB', 'Манчестер',
  35, 56.0, 40000, 16000,
  3.30, 3.60, 6.5, 90, false, null,
  '{"A-levels / IB / Foundation"}', true,
  'Для выпускников 11-летней школы нужен Foundation-год (INTO Manchester) или A-levels/IB.',
  '{English}', '{engineering,business,cs,science,medicine,humanities,economics,social}',
  '{"Computer Science","Mechanical Engineering","Accounting & Finance","Biology","Economics","Materials Science"}',
  'limited', 'Global Futures Scholarship — частичные гранты для студентов из отдельных стран.',
  '[{"label":"UCAS — основной дедлайн","month":1,"day":14}]', 'Сентябрь',
  'Исследовательский университет из Russell Group, где открыли графен и построили первый компьютер с хранимой программой. Жизнь дешевле, чем в Лондоне.',
  '{"25 нобелевских лауреатов","Дешевле Лондона","Сильная инженерия и CS"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/University_of_Manchester_building%2C_Oxford_Road_-_DSC05626.JPG/1280px-University_of_Manchester_building%2C_Oxford_Road_-_DSC05626.JPG',
  'Rept0n1x · CC BY-SA 3.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:University_of_Manchester_building,_Oxford_Road_-_DSC05626.JPG',
  'https://www.manchester.ac.uk', 'https://www.manchester.ac.uk/study/undergraduate/',
  'manchester.ac.uk, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'tum', 'Technical University of Munich', 'Мюнхенский технический университет',
  'Германия', 'DE', 'Мюнхен',
  26, null, 5500, 14000,
  3.50, 3.70, 6.5, 88, false, null,
  '{"Studienkolleg / 1 год вуза"}', true,
  'С аттестатом 11 классов прямой доступ закрыт: нужен Studienkolleg (подготовительный колледж) или 1–2 курса вуза на родине.',
  '{German,English}', '{engineering,cs,science,math,business}',
  '{"Informatics","Mechanical Engineering","Management & Technology","Electrical Engineering","Aerospace","Physics"}',
  'limited', 'Deutschlandstipendium — 300 € в месяц; с 2024 для студентов не из ЕС плата 2–3 тыс. € за семестр.',
  '[{"label":"Зимний семестр","month":7,"day":15},{"label":"Летний семестр","month":1,"day":15}]', 'Октябрь',
  'Лучший технический вуз Германии и ЕС: сильнейшая инженерия, тесные связи с BMW, Siemens и Airbus.',
  '{"№1 в ЕС по QS","Низкая стоимость обучения","Стажировки в крупнейших компаниях"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Arcisstr._21_TUM_Muenchen-1.jpg/1280px-Arcisstr._21_TUM_Muenchen-1.jpg',
  'Rufus46 · CC BY-SA 3.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Arcisstr._21_TUM_Muenchen-1.jpg',
  'https://www.tum.de/en/', 'https://www.tum.de/en/studies/application',
  'tum.de, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'tu-delft', 'Delft University of Technology', 'Делфтский технический университет',
  'Нидерланды', 'NL', 'Делфт',
  47, null, 19500, 15000,
  3.40, 3.70, 6.5, 90, false, null,
  '{"Numerus fixus selection"}', true,
  'Обычно нужен аттестат + год обучения в вузе или признанный Foundation; на Aerospace и CSE — отбор numerus fixus.',
  '{English}', '{engineering,cs,architecture,science,design}',
  '{"Aerospace Engineering","Computer Science & Engineering","Nanobiology","Applied Earth Sciences","Architecture"}',
  'limited', 'NL Scholarship (бывш. Holland Scholarship) — 5 000 € на первый год для студентов не из ЕЭЗ.',
  '[{"label":"Программы с numerus fixus","month":1,"day":15},{"label":"Остальные программы","month":4,"day":1}]', 'Сентябрь',
  'Главный технический университет Нидерландов: авиакосмос, робототехника и водные технологии мирового уровня.',
  '{"Топ-50 мира","Обучение на английском","Сильнейшая аэрокосмическая школа"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/TU_Delft_Universiteitsbibliotheek.jpg/1280px-TU_Delft_Universiteitsbibliotheek.jpg',
  'Choinowski · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:TU_Delft_Universiteitsbibliotheek.jpg',
  'https://www.tudelft.nl/en/', 'https://www.tudelft.nl/en/education/admission-and-application',
  'tudelft.nl, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'polimi', 'Politecnico di Milano', 'Миланский политехнический университет',
  'Италия', 'IT', 'Милан',
  111, null, 4300, 14000,
  3.20, 3.50, 6.0, 78, false, 1300,
  '{"TOL / SAT"}', true,
  'Италия требует 12 лет школы: после 11 классов нужен 1 курс вуза или Foundation. Вступительный тест TOL можно заменить SAT.',
  '{English,Italian}', '{engineering,architecture,design,cs}',
  '{"Engineering of Computing Systems","Mechanical Engineering","Architectural Design","Design & Engineering","Civil Engineering"}',
  'full', 'Региональная стипендия DSU Lombardia зависит от дохода семьи: освобождение от платы + до ~7 000 € в год.',
  '[{"label":"Первая волна (иностранцы)","month":11,"day":15},{"label":"Последняя волна","month":4,"day":1}]', 'Сентябрь',
  'Лучший технический вуз Италии и один из сильнейших в мире по дизайну и архитектуре. Низкая плата и стипендии по доходу.',
  '{"Топ-10 мира по дизайну","Плата ≈ 4 тыс. $ в год","Стипендия DSU по доходу семьи"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Polimi_Leonardo_campus_main_building.jpg/1280px-Polimi_Leonardo_campus_main_building.jpg',
  'NuclearNiranjan · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Polimi_Leonardo_campus_main_building.jpg',
  'https://www.polimi.it/en', 'https://www.polimi.it/en/prospective-students',
  'polimi.it, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'charles', 'Charles University', 'Карлов университет',
  'Чехия', 'CZ', 'Прага',
  246, null, 8000, 11000,
  3.00, 3.40, 6.0, 80, false, null,
  '{"Вступительные экзамены факультета","Нострификация аттестата"}', false,
  'Аттестат нужно нострифицировать (признать) в Чехии до зачисления.',
  '{Czech,English}', '{medicine,humanities,law,science,cs,math,social}',
  '{"General Medicine","Computer Science","Mathematics","International Relations","Psychology","Chemistry"}',
  'partial', 'Обучение на чешском языке бесплатное (нужен уровень B2). Англоязычные программы платные.',
  '[{"label":"Большинство факультетов","month":2,"day":28},{"label":"Медицина на английском","month":3,"day":31}]', 'Октябрь',
  'Старейший университет Центральной Европы (1348). Бесплатное обучение на чешском и доступная жизнь в Праге.',
  '{"Бесплатно на чешском языке","Недорогая жизнь в Праге","Сильная медицина"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Praha%2C_Univerzita_Karlova_-_Karolinum.jpg/1280px-Praha%2C_Univerzita_Karlova_-_Karolinum.jpg',
  'Stanislav Dusík · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Praha,_Univerzita_Karlova_-_Karolinum.jpg',
  'https://cuni.cz/UKEN-1.html', 'https://cuni.cz/UKEN-1.html',
  'cuni.cz, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'kaist', 'KAIST', 'Корейский институт передовых технологий (KAIST)',
  'Южная Корея', 'KR', 'Тэджон',
  53, null, 11000, 8000,
  3.50, 3.80, 6.5, 83, false, null,
  '{}', false, null,
  '{English,Korean}', '{engineering,cs,science,math,business}',
  '{"Computer Science","Electrical Engineering","Mechanical Engineering","Bio & Brain Engineering","Industrial Design"}',
  'full', 'KAIST International Student Scholarship: полная оплата обучения + ежемесячная стипендия большинству принятых иностранцев.',
  '[{"label":"1-й раунд","month":10,"day":1},{"label":"2-й раунд","month":1,"day":10}]', 'Сентябрь',
  'Лучший технический вуз Кореи: обучение на английском, почти все иностранцы учатся бесплатно со стипендией.',
  '{"Обучение и стипендия покрыты","Преподавание на английском","Связи с Samsung и LG"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/KAIST_fountains_view.jpg/1280px-KAIST_fountains_view.jpg',
  'AhmadElq · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:KAIST_fountains_view.jpg',
  'https://www.kaist.ac.kr/en/', 'https://admission.kaist.ac.kr/intl-undergraduate/',
  'kaist.ac.kr, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'nus', 'National University of Singapore', 'Национальный университет Сингапура',
  'Сингапур', 'SG', 'Сингапур',
  8, 5.0, 30000, 14000,
  3.70, 3.90, 6.5, 92, true, 1450,
  '{SAT}', false, null,
  '{English}', '{cs,engineering,business,medicine,science,law,design}',
  '{"Computer Science","Business Analytics","Engineering","Data Science & Economics","Law","Architecture"}',
  'partial', 'MOE Tuition Grant снижает плату примерно вдвое, но требует 3 года работы в Сингапуре после выпуска.',
  '[{"label":"Международные аттестаты","month":2,"day":23}]', 'Август',
  'Лучший университет Азии по QS: сильнейшие CS и бизнес, английский язык обучения и финансовый хаб Юго-Восточной Азии.',
  '{"№1 в Азии","Tuition Grant от государства","Карьера в Сингапуре"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/University_Town_Skyline_from_Northwest_Kent_Ridge_Campus%2C_National_University_of_Singapore%2C_February_2020.jpg/1280px-University_Town_Skyline_from_Northwest_Kent_Ridge_Campus%2C_National_University_of_Singapore%2C_February_2020.jpg',
  'Joshua Rommel Hayag Vargas · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:University_Town_Skyline_from_Northwest_Kent_Ridge_Campus,_National_University_of_Singapore,_February_2020.jpg',
  'https://nus.edu.sg', 'https://www.nus.edu.sg/oam/',
  'nus.edu.sg/oam, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'melbourne', 'The University of Melbourne', 'Мельбурнский университет',
  'Австралия', 'AU', 'Мельбурн',
  19, 70.0, 34000, 16000,
  3.30, 3.60, 6.5, 79, false, null,
  '{Foundation}', true,
  'После 11 классов обычно нужен Trinity College Foundation Studies (1 год) или IB/A-levels.',
  '{English}', '{science,business,arts,design,cs,medicine,humanities}',
  '{"Bachelor of Science","Bachelor of Commerce","Bachelor of Design","Bachelor of Biomedicine","Bachelor of Arts"}',
  'partial', 'Melbourne International Undergraduate Scholarship: 10 000 AUD, 50% или 100% скидка на обучение.',
  '[{"label":"Семестр 1 (февраль)","month":11,"day":30},{"label":"Семестр 2 (июль)","month":5,"day":31}]', 'Февраль / Июль',
  'Лучший университет Австралии: гибкая «мельбурнская модель» — широкий бакалавриат и специализация позже, право работать во время учёбы.',
  '{"№1 в Австралии","Два набора в год","Можно работать во время учёбы"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Old_Arts_Building%2C_University_of_Melbourne_%282650414285%29.jpg/1280px-Old_Arts_Building%2C_University_of_Melbourne_%282650414285%29.jpg',
  'cogdogblog · CC0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Old_Arts_Building,_University_of_Melbourne_(2650414285).jpg',
  'https://www.unimelb.edu.au', 'https://study.unimelb.edu.au/',
  'unimelb.edu.au, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'nazarbayev', 'Nazarbayev University', 'Назарбаев Университет',
  'Казахстан', 'KZ', 'Астана',
  null, 25.0, 14000, 6000,
  3.20, 3.60, 6.5, 79, false, 1400,
  '{NUET,SAT}', false,
  'При IELTS 5.5–6.0 можно поступить на Foundation Year Program.',
  '{English}', '{engineering,cs,science,medicine,business,social,humanities,math}',
  '{"Computer Science","Robotics","Chemical Engineering","Economics","Medicine (MD)","Political Science"}',
  'full', 'Государственный грант для граждан РК покрывает обучение и стипендию; для иностранцев есть отдельные гранты.',
  '[{"label":"Основной приём","month":3,"day":1},{"label":"Последняя сессия NUET","month":4,"day":15}]', 'Август',
  'Англоязычный исследовательский университет в Астане с западными партнёрами (Duke, UCL, Pittsburgh). Грант покрывает всё обучение.',
  '{"Грант покрывает обучение","Обучение на английском","Партнёрства с топ-вузами"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Nazarbayev_University_2.jpg/1280px-Nazarbayev_University_2.jpg',
  'Dinononozavr1 · CC BY-SA 4.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Nazarbayev_University_2.jpg',
  'https://nu.edu.kz', 'https://admissions.nu.edu.kz/',
  'nu.edu.kz (ориентировочно)', true, '2026-09-01'
),
(
  'hku', 'The University of Hong Kong', 'Гонконгский университет',
  'Гонконг', 'HK', 'Гонконг',
  11, 10.0, 23300, 13000,
  3.50, 3.80, 6.5, 90, false, 1350,
  '{}', false, null,
  '{English}', '{medicine,law,business,cs,engineering,architecture,social}',
  '{"Computer Science","Business & Finance","Law","Medicine","Architecture","Data Science"}',
  'partial', 'HKU Entrance Scholarships for International Students — от частичного до полного покрытия.',
  '[{"label":"Ранний раунд","month":11,"day":14},{"label":"Основной раунд","month":1,"day":8}]', 'Сентябрь',
  'Старейший университет Гонконга с преподаванием на английском, сильными бизнесом, правом и медициной и выходом на рынок Азии.',
  '{"Топ-15 мира","Обучение на английском","Стипендии для иностранцев"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Main_Building_HKU_20100926_03.JPG/1280px-Main_Building_HKU_20100926_03.JPG',
  'Ka-Fai,So · CC BY-SA 3.0 · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Main_Building_HKU_20100926_03.JPG',
  'https://www.hku.hk', 'https://admissions.hku.hk/',
  'admissions.hku.hk, QS WUR (ориентировочно)', true, '2026-09-01'
),
(
  'koc', 'Koç University', 'Университет Коч',
  'Турция', 'TR', 'Стамбул',
  null, 30.0, 38000, 9000,
  3.30, 3.60, 6.5, 80, true, 1350,
  '{SAT}', false, null,
  '{English}', '{engineering,business,economics,law,medicine,social,humanities,cs,science}',
  '{"Computer Engineering","Business Administration","Economics","International Relations","Law","Molecular Biology"}',
  'full', 'Merit-стипендии Koç: 100%, 50% или 25% оплаты обучения по результатам SAT и школьных оценок.',
  '[{"label":"Ранний приём","month":1,"day":15},{"label":"Основной приём","month":4,"day":15}]', 'Сентябрь',
  'Частный исследовательский университет в Стамбуле с обучением на английском и щедрыми merit-стипендиями.',
  '{"Стипендии до 100%","Обучение на английском","Кампус у Босфора"}',
  'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Ko%C3%A7University2.jpg/1280px-Ko%C3%A7University2.jpg',
  'Jorge1767 · Public domain · Wikimedia Commons',
  'https://commons.wikimedia.org/wiki/File:Ko%C3%A7University2.jpg',
  'https://www.ku.edu.tr/en/', 'https://international.ku.edu.tr/',
  'ku.edu.tr (ориентировочно)', true, '2026-09-01'
);

-- ---------------------------------------------------------------------
-- Scholarships
-- ---------------------------------------------------------------------

insert into public.scholarships (
  slug, name, provider, country_code, university_id, coverage, amount_note,
  eligible_citizenships, min_gpa_4, min_ielts, need_based, deadline, description, url, is_demo
)
select
  s.slug, s.name, s.provider, s.country_code, u.id, s.coverage, s.amount_note,
  s.eligible_citizenships, s.min_gpa_4, s.min_ielts, s.need_based, s.deadline::jsonb,
  s.description, s.url, true
from (values
  ('mit-financial-aid', 'MIT Need-Based Financial Aid', 'MIT', 'US', 'mit', 'full',
   '100% подтверждённой потребности семьи', null::text[], 3.90, 7.0, true,
   '{"label":"CSS Profile","month":2,"day":15}',
   'MIT не учитывает платёжеспособность при приёме и закрывает всю финансовую потребность, в том числе иностранцам.',
   'https://sfs.mit.edu/'),
  ('asu-new-american', 'New American University International Scholarship', 'Arizona State University', 'US', 'asu', 'partial',
   'Частичное покрытие обучения ежегодно', null, 3.00, 6.0, false,
   '{"label":"Подача заявления в ASU","month":5,"day":1}',
   'Merit-стипендия: рассматривается автоматически при подаче заявления, размер зависит от GPA.',
   'https://tuition.asu.edu/financial-aid/scholarships'),
  ('lester-b-pearson', 'Lester B. Pearson International Scholarship', 'University of Toronto', 'CA', 'toronto', 'full',
   'Обучение, проживание и книги на 4 года', null, 3.80, 6.5, false,
   '{"label":"Номинация школы","month":11,"day":7}',
   'Для иностранцев с выдающимися оценками и лидерством. Школа должна номинировать ученика.',
   'https://future.utoronto.ca/pearson-scholarships'),
  ('ucl-global-ug', 'UCL Global Undergraduate Scholarship', 'University College London', 'GB', 'ucl', 'partial',
   'Проживание и/или оплата обучения', null, 3.60, 7.0, true,
   '{"label":"Заявка после оффера","month":4,"day":30}',
   'Для сильных студентов из семей с низким доходом, которые не смогли бы учиться в UCL без поддержки.',
   'https://www.ucl.ac.uk/scholarships/'),
  ('deutschlandstipendium', 'Deutschlandstipendium', 'Правительство Германии и спонсоры', 'DE', 'tum', 'stipend',
   '300 € в месяц', null, 3.50, null, false,
   '{"label":"Приём заявок в TUM","month":8,"day":31}',
   'Merit-стипендия для студентов немецких вузов независимо от гражданства и дохода.',
   'https://www.deutschlandstipendium.de/'),
  ('nl-scholarship', 'NL Scholarship (бывш. Holland Scholarship)', 'Министерство образования Нидерландов', 'NL', 'tu-delft', 'partial',
   '5 000 € на первый год', null, 3.40, 6.5, false,
   '{"label":"Заявка","month":2,"day":1}',
   'Разовая стипендия для студентов не из ЕЭЗ, поступающих в нидерландские вузы.',
   'https://www.studyinnl.org/finances/nl-scholarship'),
  ('dsu-lombardia', 'Стипендия DSU (Regione Lombardia)', 'Politecnico di Milano', 'IT', 'polimi', 'full',
   'Освобождение от платы + до ~7 000 € в год', null, null, 6.0, true,
   '{"label":"Заявка DSU","month":7,"day":31}',
   'Региональная стипендия по доходу семьи: покрывает плату за обучение и часть расходов на жизнь.',
   'https://www.polimi.it/en/prospective-students'),
  ('czech-tuition-free', 'Бесплатное обучение на чешском языке', 'Чешская Республика', 'CZ', 'charles', 'tuition',
   '0 € за обучение', null, null, null, false,
   '{"label":"Подача в Карлов университет","month":2,"day":28}',
   'Государственные вузы Чехии не берут плату за программы на чешском — нужен уровень языка B2.',
   'https://cuni.cz/UKEN-1.html'),
  ('kaist-international', 'KAIST International Student Scholarship', 'KAIST', 'KR', 'kaist', 'full',
   'Обучение + ежемесячная стипендия', null, 3.50, 6.5, false,
   '{"label":"1-й раунд KAIST","month":10,"day":1}',
   'Назначается большинству принятых иностранных бакалавров по результатам отбора.',
   'https://admission.kaist.ac.kr/intl-undergraduate/'),
  ('gks-undergraduate', 'Global Korea Scholarship (GKS) — бакалавриат', 'Правительство Республики Корея', 'KR', null, 'full',
   'Обучение, проживание, перелёт, год корейского', null, 3.20, null, false,
   '{"label":"Подача через посольство","month":10,"day":1}',
   'Государственная стипендия Кореи для иностранцев с годом подготовки по корейскому языку.',
   'https://www.studyinkorea.go.kr'),
  ('moe-tuition-grant', 'MOE Tuition Grant', 'Министерство образования Сингапура', 'SG', 'nus', 'partial',
   'Снижение платы примерно вдвое', null, 3.70, 6.5, false,
   '{"label":"После оффера NUS","month":6,"day":1}',
   'Субсидия на обучение в обмен на обязательство отработать 3 года в Сингапуре.',
   'https://www.nus.edu.sg/oam/'),
  ('melbourne-intl-ug', 'Melbourne International Undergraduate Scholarship', 'University of Melbourne', 'AU', 'melbourne', 'partial',
   '10 000 AUD, 50% или 100% скидка', null, 3.60, 6.5, false,
   '{"label":"Рассматривается с заявкой","month":11,"day":30}',
   'Автоматически рассматривается для сильных иностранных абитуриентов.',
   'https://study.unimelb.edu.au/'),
  ('nu-state-grant', 'Государственный грант Назарбаев Университета', 'Республика Казахстан', 'KZ', 'nazarbayev', 'full',
   'Обучение + ежемесячная стипендия', '{KZ}', 3.20, 6.5, false,
   '{"label":"Основной приём NU","month":3,"day":1}',
   'Покрывает полную стоимость обучения для граждан Казахстана, поступивших по конкурсу.',
   'https://admissions.nu.edu.kz/'),
  ('hku-entrance-intl', 'HKU Entrance Scholarships for International Students', 'The University of Hong Kong', 'HK', 'hku', 'partial',
   'От частичного до полного покрытия', null, 3.70, 6.5, false,
   '{"label":"Основной раунд HKU","month":1,"day":8}',
   'Merit-стипендии для иностранных первокурсников с выдающимися результатами.',
   'https://admissions.hku.hk/'),
  ('koc-merit', 'Koç University Merit Scholarship', 'Koç University', 'TR', 'koc', 'full',
   '100%, 50% или 25% оплаты обучения', null, 3.30, 6.5, false,
   '{"label":"Основной приём Koç","month":4,"day":15}',
   'Назначается по SAT и школьным оценкам при поступлении.',
   'https://international.ku.edu.tr/'),
  ('turkiye-burslari', 'Türkiye Bursları', 'Правительство Турции', 'TR', null, 'full',
   'Обучение, общежитие, стипендия, перелёт, год турецкого', null, 3.00, null, false,
   '{"label":"Заявка","month":2,"day":20}',
   'Государственная стипендия Турции для иностранцев на все уровни обучения.',
   'https://www.turkiyeburslari.gov.tr')
) as s (
  slug, name, provider, country_code, university_slug, coverage, amount_note,
  eligible_citizenships, min_gpa_4, min_ielts, need_based, deadline, description, url
)
left join public.universities u on u.slug = s.university_slug;
-- UniRoute · supabase/migrations/20260917120026_seed_universities.sql
